### ISSUE TITLE
Use of std:fill is dubious

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/autodiff#13]
Hi @zsmith3 

I've just written https://github.com/awf/autodiff/commit/4d127b82712295d7e87f705b5ccd9a0746a36217 to partially correct https://github.com/awf/autodiff/commit/84184f50c890579812d53a52e15dd7b83f997482.  I can't help thinking that the usage of `std:fill` in the latter commit was accidental.  The latter seems to be indended as a purely documentation commit.

In any case, I don't think that any of the `std:fill` calls needed `sizeof(double)` and one of them was missing an initial `J`.

Do you remember the original purpose of this commit, or whether it was accidental?  It was causing Manual to error out with heap corruption on Azure DevOps and on an Azure VS VM I set up (but, strangely, not on my local machine).

Thanks

**Comment by zsmith3** [comment]
As I recall, I replaced all of the `memset` with `std::fill` (intentionally) because I was told to do so (presumably in person as I can't find any record of it here). I think this was just because `std::fill` is the preferred method in C++.  I didn't properly understand either function so just copied the whole expression, including the `sizeof(double)`, and left it because it seemed to work for me - it looks like removing the `sizeof(double)` from each is the right thing to do now.

**Comment by awf** [comment]
Thanks both, and my apologies for not catching those sizeofs the first time round.

**Comment by awf** [comment]
I would say use fill with corrected bounds.  It's important that such code is idiomatic as well as performant.

--
Sent using SwiftKey on a mobile device.

**Comment by tomjaguarpaw** [comment]
Fixed by https://github.com/awf/autodiff/commit/3bf588056defb27f5fb1a71396691e1be7b3013f
